### ISSUE TITLE
PasswordWorker.passwordHasNormalForm:36

### ISSUE THREAD

**Issue by Nop1ks** [Nop1ks/Immutable#1]
if(password.length()>=MINIMAL_PASSWORD_LENGTH) return false;

I think there must be "<" instead of ">=".

**Comment by z13z** [comment]
done :)

**Comment by Nop1ks** [comment]
Also I think this method should be rewritten:
true : if password contains only mix of digits and letters
false: otherwise

**Comment by Nop1ks** [comment]
Also please add missing public methods from PasswordWorker to PasswordWorkerInterface
